-- ============================================================
-- Ponte Digital -- Recursos Adicionais Camada A
-- Distrito de Lisboa -- Todos os Municípios
-- Maio 2026
-- ============================================================

-- EMPREGO: Centros de Emprego do Distrito de Lisboa

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Emprego de Sintra', 'Apoio na procura de emprego, inscrição no desemprego e formação profissional no município de Sintra.', 3, 'IEFP', 'Av. Movimento das Forcas Armadas 3, 2710-413 Sintra', 2, 'Sintra', ST_MakePoint(-9.3881, 38.8026), '219 107 100', 'https://www.iefp.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Desempregados e pessoas à procura de emprego', 'Comparecer com Cartão de Cidadão. Inscrição gratuita.', TRUE, TRUE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Emprego de Cascais', 'Apoio na procura de emprego, inscrição no desemprego e formação profissional no município de Cascais.', 3, 'IEFP', 'Rua Padre Américo 5, 2750-201 Cascais', 4, 'Cascais', ST_MakePoint(-9.4218, 38.6979), '214 867 900', 'https://www.iefp.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Desempregados e pessoas à procura de emprego', 'Comparecer com Cartão de Cidadão. Inscrição gratuita.', TRUE, TRUE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descicao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Emprego de Loures', 'Apoio na procura de emprego, inscrição no desemprego e formação profissional no município de Loures.', 3, 'IEFP', 'Av. Jose Saramago 18, 2674-502 Loures', 3, 'Loures', ST_MakePoint(-9.1681, 38.8313), '219 317 000', 'https://www.iefp.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Desempregados e pessoas à procura de emprego', 'Comparecer com Cartão de Cidadão. Inscrição gratuita.', TRUE, TRUE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Emprego da Amadora', 'Apoio na procura de emprego, inscrição no desemprego e formação profissional no município da Amadora.', 3, 'IEFP', 'Rua Eca de Queiros 33, 2700-327 Amadora', 6, 'Amadora', ST_MakePoint(-9.2236, 38.7566), '214 967 000', 'https://www.iefp.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Desempregados e pessoas à procura de emprego', 'Comparecer com Cartão de Cidadão. Inscrição gratuita.', TRUE, TRUE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Emprego de Torres Vedras', 'Apoio na procura de emprego, inscrição no desemprego e formação profissional no município de Torres Vedras.', 3, 'IEFP', 'Rua Serpa Pinto 10, 2560-275 Torres Vedras', 10, 'Torres Vedras', ST_MakePoint(-9.2597, 39.0919), '261 324 400', 'https://www.iefp.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Desempregados e pessoas à procura de emprego', 'Comparecer com Cartão de Cidadão. Inscrição gratuita.', TRUE, FALSE, FALSE, 'A', 'IEFP');

-- ALIMENTACAO: Bancos Alimentares e Cantinas

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Cantina Social da Amadora', 'Refeicoes sociais gratuitas ou a preco simbolico para residentes da Amadora em situacao de carencia.', 1, 'Camara Municipal da Amadora', 'Av. General Humberto Delgado, 2700-327 Amadora', 6, 'Amadora', ST_MakePoint(-9.2250, 38.7540), '214 975 200', 'https://www.cm-amadora.pt', '{"segunda":"12:00-14:00","terca":"12:00-14:00","quarta":"12:00-14:00","quinta":"12:00-14:00","sexta":"12:00-14:00"}', 'Residentes da Amadora em situacao de carencia economica', 'Inscricao previa nos servicos sociais da Camara.', TRUE, FALSE, FALSE, 'A', 'Camara Municipal da Amadora');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Banco Alimentar de Loures', 'Distribuicao de generos alimenticios a familias carenciadas do municipio de Loures.', 1, 'Misericordia de Loures', 'R. Gago Coutinho 14, 2674-502 Loures', 3, 'Loures', ST_MakePoint(-9.1690, 38.8300), '219 382 130', 'https://www.misericordiadeloures.pt', '{"segunda":"09:00-12:00","quarta":"09:00-12:00","sexta":"09:00-12:00"}', 'Familias carenciadas do municipio de Loures', 'Inscricao previa. Apresentar comprovativo de residencia.', TRUE, FALSE, FALSE, 'A', 'Misericordia de Loures');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Cantina Social de Mafra', 'Refeicoes sociais para residentes do municipio de Mafra em situacao de vulnerabilidade.', 1, 'Camara Municipal de Mafra', 'Terreiro D. Joao V, 2640-452 Mafra', 9, 'Mafra', ST_MakePoint(-9.3318, 38.9375), '261 816 100', 'https://www.cm-mafra.pt', '{"segunda":"12:00-14:00","terca":"12:00-14:00","quarta":"12:00-14:00","quinta":"12:00-14:00","sexta":"12:00-14:00"}', 'Residentes do municipio de Mafra em carencia economica', 'Inscricao previa nos servicos sociais da Camara.', TRUE, FALSE, FALSE, 'A', 'Camara Municipal de Mafra');

-- SAUDE: Centros de saude e apoio medico

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Saude de Sintra', 'Cuidados de saude primarios para residentes do municipio de Sintra.', 2, 'ACES Sintra', 'Av. Almirante Reis 12, 2710-589 Sintra', 2, 'Sintra', ST_MakePoint(-9.3950, 38.7980), '219 238 200', 'https://www.sns.gov.pt', '{"segunda":"08:00-20:00","terca":"08:00-20:00","quarta":"08:00-20:00","quinta":"08:00-20:00","sexta":"08:00-20:00"}', 'Residentes do municipio de Sintra com cartao de utente', 'Cartao de utente do SNS ou numero de utente.', TRUE, TRUE, FALSE, 'A', 'SNS');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Saude da Amadora', 'Cuidados de saude primarios para residentes do municipio da Amadora.', 2, 'ACES Amadora', 'Rua Alfredo da Silva 1, 2700-327 Amadora', 6, 'Amadora', ST_MakePoint(-9.2270, 38.7520), '214 975 100', 'https://www.sns.gov.pt', '{"segunda":"08:00-20:00","terca":"08:00-20:00","quarta":"08:00-20:00","quinta":"08:00-20:00","sexta":"08:00-20:00"}', 'Residentes da Amadora com cartao de utente', 'Cartao de utente do SNS ou numero de utente.', TRUE, TRUE, FALSE, 'A', 'SNS');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Saude de Torres Vedras', 'Cuidados de saude primarios para residentes do municipio de Torres Vedras.', 2, 'ACES Oeste Norte', 'Rua Dr. Antonio Lopes Borba, 2560-275 Torres Vedras', 10, 'Torres Vedras', ST_MakePoint(-9.2620, 39.0900), '261 336 200', 'https://www.sns.gov.pt', '{"segunda":"08:00-20:00","terca":"08:00-20:00","quarta":"08:00-20:00","quinta":"08:00-20:00","sexta":"08:00-20:00"}', 'Residentes de Torres Vedras com cartao de utente', 'Cartao de utente do SNS ou numero de utente.', TRUE, FALSE, FALSE, 'A', 'SNS');

-- APOIO SOCIAL

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Servico de Accao Social de Cascais', 'Apoio social, encaminhamento e informacao sobre prestacoes sociais para residentes de Cascais.', 4, 'Camara Municipal de Cascais', 'Av. 25 de Abril, 2754-502 Cascais', 4, 'Cascais', ST_MakePoint(-9.4210, 38.6960), '214 825 000', 'https://www.cm-cascais.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Residentes do municipio de Cascais em situacao de vulnerabilidade', 'Contactar para marcacao previa.', TRUE, TRUE, FALSE, 'A', 'Camara Municipal de Cascais');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro de Accao Social de Oeiras', 'Apoio social, encaminhamento e informacao sobre prestacoes sociais para residentes de Oeiras.', 4, 'Camara Municipal de Oeiras', 'Av. Eng. Francisco Bianchi 1, 2780-117 Oeiras', 5, 'Oeiras', ST_MakePoint(-9.3149, 38.6979), '214 405 000', 'https://www.cm-oeiras.pt', '{"segunda":"09:00-13:00","terca":"09:00-13:00","quarta":"09:00-13:00","quinta":"09:00-13:00","sexta":"09:00-13:00"}', 'Residentes do municipio de Oeiras em situacao de vulnerabilidade', 'Contactar para marcacao previa.', TRUE, FALSE, FALSE, 'A', 'Camara Municipal de Oeiras');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Misericordia de Mafra -- Apoio Social', 'Apoio social, distribuicao de bens e encaminhamento para residentes do municipio de Mafra.', 4, 'Santa Casa da Misericordia de Mafra', 'Rua Serpa Pinto 5, 2640-452 Mafra', 9, 'Mafra', ST_MakePoint(-9.3310, 38.9360), '261 817 800', 'https://www.scmmafra.pt', '{"segunda":"09:00-12:30","terca":"09:00-12:30","quarta":"09:00-12:30","quinta":"09:00-12:30","sexta":"09:00-12:30"}', 'Residentes do municipio de Mafra em situacao de carencia', 'Contactar por telefone para marcacao.', TRUE, FALSE, FALSE, 'A', 'Santa Casa da Misericordia de Mafra');

-- EDUCACAO

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro Qualifica de Sintra', 'Cursos de formacao de adultos, certificacao escolar e profissional gratuitos para adultos.', 5, 'IEFP / Centro de Formacao de Sintra', 'Av. Heliodoro Salgado 10, 2710-589 Sintra', 2, 'Sintra', ST_MakePoint(-9.3870, 38.8010), '219 107 200', 'https://www.iefp.pt', '{"segunda":"09:00-17:00","terca":"09:00-17:00","quarta":"09:00-17:00","quinta":"09:00-17:00","sexta":"09:00-17:00"}', 'Adultos sem o 12o ano ou sem qualificacao profissional', 'Inscricao gratuita. Maiores de 18 anos.', TRUE, TRUE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Centro Qualifica da Amadora', 'Cursos de formacao de adultos, certificacao escolar e profissional gratuitos.', 5, 'IEFP / Centro de Formacao da Amadora', 'Rua Eca de Queiros 35, 2700-327 Amadora', 6, 'Amadora', ST_MakePoint(-9.2240, 38.7550), '214 967 100', 'https://www.iefp.pt', '{"segunda":"09:00-17:00","terca":"09:00-17:00","quarta":"09:00-17:00","quinta":"09:00-17:00","sexta":"09:00-17:00"}', 'Adultos sem o 12o ano ou sem qualificacao profissional', 'Inscricao gratuita. Maiores de 18 anos.', TRUE, FALSE, FALSE, 'A', 'IEFP');

INSERT INTO recurso (nome, descricao, categoria_id, organizacao, morada, municipio_id, freguesia, geom, telefone, website, horario, publico_alvo, condicoes_acesso, activo, verificado, urgente, camada, fonte) VALUES
('Biblioteca Municipal de Torres Vedras -- Formacao Digital', 'Formacao gratuita em informatica e literacia digital para adultos.', 5, 'Camara Municipal de Torres Vedras', 'Rua Serpa Pinto 14, 2560-275 Torres Vedras', 10, 'Torres Vedras', ST_MakePoint(-9.2580, 39.0910), '261 310 500', 'https://www.cm-tvedras.pt', '{"segunda":"18:00-20:00","quarta":"18:00-20:00","sexta":"14:00-16:00"}', 'Adultos com baixa literacia digital', 'Inscricao gratuita na biblioteca municipal.', TRUE, FALSE, FALSE, 'A', 'Camara Municipal de Torres Vedras');
